### ISSUE TITLE
请教下为何用自己的解析器生成器？

### ISSUE THREAD

**Issue by nobodxbodon** [AoiKuiyuyou/SichuanLang#1]
（从[这里](https://github.com/zhanyong-wan/dongbei/issues/84#issuecomment-597063394)找来）
而不是用现成的比如 rply？最近在尝试[重现木兰](https://github.com/MulanRevive/bounty/issues/4)，想研究下不同的实现方案。

**Comment by AoiKuiyuyou** [comment]
- 因为 [AoikTopDownParser](https://github.com/AoiKuiyuyou/AoikTopDownParser) 是自己开发的，对代码熟悉所以更方便根据自己的需求做定制。
- 生成的解析器，全部代码在一个文件内，对生成库本身无依赖，解析逻辑的实现是很直观的。如果对生成库有依赖，那么解析逻辑是在生成库内部实现的，做定制就不那么容易。
- 支持在解析器的语法规则中嵌入代码。
- 支持自定义生成的解析器文件的模版，可加入额外的代码如引入语句，这样生成的文件就是一个功能完整的解析器模块，无需做额外的手动编辑。
